"""Representation of arrotolata data protos in python."""

import dataclasses
from enum import Enum
from typing import Optional


class DeviceMeasurementType(Enum):
    """Device measurement types."""
    UNKNOWN_MEASUREMENT = 0
    MEASUREMENT_ALTITUDE = 1
    MEASUREMENT_PRESSURE = 2
    MEASUREMENT_HUMIDITY = 3
    MEASUREMENT_BATTERY_LEVEL = 4
    MEASUREMENT_GALVANIC_SKIN_RESPONSE = 5
    MEASUREMENT_TEMPERATURE = 6
    MEASUREMENT_PULSE_RATE = 7
    MEASUREMENT_ACTIVITY_INTENSITY = 8
    MEASUREMENT_AMBIENT_LIGHT = 9
    MEASUREMENT_BATTERY_STATUS = 10
    MEASUREMENT_WEIGHT = 11
    MEASUREMENT_HEIGHT = 12
    MEASUREMENT_SUBSYSTEM_STATUS = 13
    MEASUREMENT_RAW_CAP_SENSE = 14
    MEASUREMENT_AMBIENT_TEMPERATURE = 15
    MEASUREMENT_FIREHOSE = 16
    MEASUREMENT_ACCELEROMETER_FEATURES = 17
    MEASUREMENT_MULTISPECTRAL_LIGHT = 18
    MEASUREMENT_ACTIVITY_CONTEXT = 19
    MEASUREMENT_HEART_RATE = 20
    MEASUREMENT_BLOOD_PRESSURE = 21
    MEASUREMENT_PVT_RESULT = 22
    MEASUREMENT_KEYBOARD_TEST = 24
    MEASUREMENT_EVENT_TAG = 25
    MEASUREMENT_BLOOD_GLUCOSE = 26
    MEASUREMENT_PULSE_OX = 27
    MEASUREMENT_SENSOR_CONFIG = 28
    MEASUREMENT_ACTIVITY_CLASS = 29
    MEASUREMENT_FATIGUE_LEVEL = 30
    MEASUREMENT_IMU = 31
    MEASUREMENT_OPAQUE_RAW_DATA = 33
    MEASUREMENT_ECG = 34
    MEASUREMENT_EDA = 35
    MEASUREMENT_PPG = 36
    MEASUREMENT_RWAVE = 37
    MEASUREMENT_RESPIRATORY_RATE = 38
    MEASUREMENT_MPOWER_MEMORY_ACTIVITY = 39
    MEASUREMENT_MPOWER_TAPPING_ACTIVITY = 40
    MEASUREMENT_PEDOMETER = 41
    MEASUREMENT_AUDIO = 42
    MEASUREMENT_GRAVITY = 43
    MEASUREMENT_FLOORS_CLIMBED = 44
    MEASUREMENT_BLUETOOTH_PACKETS = 45
    MEASUREMENT_LUNG_EXPANSION = 57
    MEASUREMENT_SLEEP_STAGE = 58
    MEASUREMENT_SLEEP_EVENT = 80
    MEASUREMENT_EXPERIMENTAL = 59
    MEASUREMENT_FLASH_USED = 60
    MEASUREMENT_CRASH_LOG = 61
    MEASUREMENT_EEG = 62
    MEASUREMENT_EOG = 64
    MEASUREMENT_EMG = 65
    MEASUREMENT_MOCAP_TRACKING = 63
    MEASUREMENT_DEVICE_EVENT = 66
    MEASUREMENT_LOCATION = 67
    MEASUREMENT_NETWORK_TRAFFIC = 68
    MEASUREMENT_TEXT_MESSAGE = 69
    MEASUREMENT_COMMUNICATION_LOG = 70
    MEASUREMENT_PHONE_EVENT = 71
    MEASUREMENT_SYNC_CLIENT_EVENT = 72
    MEASUREMENT_NETWORK_STATS = 73
    MEASUREMENT_PROCESSOR_STATS = 74
    MEASUREMENT_CLINICAL_EVENT = 75
    MEASUREMENT_PHONE_EVENT_PING = 76
    MEASUREMENT_PHONE_EVENT_POWER = 77
    MEASUREMENT_PHONE_EVENT_PROXIMITY = 78
    MEASUREMENT_PHONE_EVENT_SCREEN = 79
    MEASUREMENT_NASAL_AIRFLOW = 81
    MEASUREMENT_NEARBY_BLUETOOTH_DEVICES = 82
    MEASUREMENT_ANDROID_ACTIVITY_DETECTION = 83
    MEASUREMENT_AMBIENT_AUDIO = 84
    MEASUREMENT_PHONE_EVENT_ANDROID_SENSOR_LIB_EVENT = 85
    MEASUREMENT_UPDRS_EVENT = 86
    MEASUREMENT_NETWORK = 87
    MEASUREMENT_NEARBY_WIFI_NETWORK = 88
    MEASUREMENT_SYNC_WEARABLE_EVENT = 89
    MEASUREMENT_PEDOMETER_ANDROID = 90
    MEASUREMENT_PEDOMETER_GFIT = 91
    MEASUREMENT_GFIT_ACTIVITY_DETECTION = 92
    MEASUREMENT_AUDIO_OUTPUT = 93
    MEASUREMENT_ALARM_VOLUMES = 100
    MEASUREMENT_ANDROID_DEVICE_DATA = 94
    MEASUREMENT_NETWORK_TRAFFIC_STATS = 95
    MEASUREMENT_APP_USAGE_STATS = 96
    MEASUREMENT_INTERSTITIAL_GLUCOSE = 97
    MEASUREMENT_APP_USAGE_STAT = 98
    MEASUREMENT_SEMANTIC_LOCATION = 99
    MEASUREMENT_APP_USAGE_STATS_EVENT = 101
    MEASUREMENT_AFIB_DETECTION = 102
    MEASUREMENT_AFIB_DETECTION_V2_RESULT = 108
    MEASUREMENT_AFIB_DETECTION_V2_DECISION = 109
    MEASUREMENT_PIEZO = 103
    MEASUREMENT_VME_APP_EVENT = 104
    MEASUREMENT_VME_SCHEDULE_CHANGE_EVENT = 105
    MEASUREMENT_VIBRATION_SEQUENCE = 106
    MEASUREMENT_NOTIFICATION = 107
    MEASUREMENT_FILE = 110
    MEASUREMENT_ECG_VOLTAGE = 111
    MEASUREMENT_ANDROID_SLEEP_API = 112
    MEASUREMENT_MYALO_TEXT_LOG = 113
    MEASUREMENT_PERMISSIONS_SENSOR = 114
    MEASUREMENT_APP_EVENT_V2 = 115
    MEASUREMENT_SLEEP_SEGMENT = 116
    MEASUREMENT_USER_REPORTED_TEMPERATURE = 117


class DerivedMetricType(Enum):
    """Derived metric types."""
    UNKNOWN_DERIVED = 0
    DERIVED_PULSE_RATE = 1
    DERIVED_RESPIRATION_RATE = 2
    DERIVED_R_WAVE = 3
    DERIVED_ECG_DISPLAY = 4
    DERIVED_SLEEP_STATE = 5
    DERIVED_SLEEP_METRICS = 32
    DERIVED_IN_BED_TIMES = 38
    DERIVED_ACTIVITY_INTENSITY_DEPRECATED = 6
    DERIVED_ACTIVITY_LABEL = 7
    DERIVED_PULSE_OX = 8
    DERIVED_PULSE_RATE_RECOVERY_REGION = 9
    DERIVED_PULSE_RATE_RECOVERY = 10
    DERIVED_PULSE_TRANSIT_TIME = 11
    DERIVED_HEART_RATE = 12
    DERIVED_HEART_RATE_VARIABILITY = 13
    DERIVED_ATRIAL_FIBRILLATION = 18
    DERIVED_SYSTOLIC_BLOOD_PRESSURE = 14
    DERIVED_DIASTOLIC_BLOOD_PRESSURE = 15
    DERIVED_TREMOR_ESTIMATION = 17
    DERIVED_GAIT_FEATURES = 19
    DERIVED_TURN_FEATURES = 20
    DERIVED_EXPERIMENTAL = 21
    DERIVED_PULSE_RATE_VARIABILITY = 22
    DERIVED_SLEEP_MOVEMENT = 23
    DERIVED_INBED_STATUS = 24
    DERIVED_SLEEP_MOVEMENT_DENSITY = 25
    DERIVED_IBI = 26
    DERIVED_IBI_METRICS = 45
    DERIVED_SLEEP_MOVEMENT_CLASS = 27
    DERIVED_SLEEP_SIGNAL_QUALITY = 28
    DERIVED_STEP_COUNT = 29
    DERIVED_ACCELEROMETER_FEATURES = 30
    DERIVED_IMU_EARTH_FRAME = 31
    DERIVED_APP_USAGE_STATS = 33
    DERIVED_PLACES_API_RESULT = 34
    DERIVED_ACTIGRAPHY_ACTIVITY_COUNT = 35
    DERIVED_ACTIGRAPHY_SLEEP = 36
    DERIVED_LOCATION_CLUSTERS = 37
    DERIVED_DATA_PHONE_CALL_EVENT = 39
    DERIVED_PPG_SIGNAL_QUALITY = 40
    DERIVED_DATA_PHONE_EVENT = 41
    DERIVED_DATA_LOCATION_LABELS = 42
    DERIVED_PULSE_PEAK = 43
    DERIVED_LABEL_EXAMPLE = 44
    DERIVED_ECG_SIGNAL_QUALITY = 46
    DERIVED_PEAK_AMPLITUDE = 47
    DERIVED_SEMANTIC_LOCATION_VISIT_EVENT = 48
    DERIVED_ECG_PQRST = 49
    DERIVED_ON_WRIST = 50
    DERIVED_PULSE_RATE_CYCLE = 51
    DERIVED_SLEEP_DISORDER = 52
    DERIVED_OVERNIGHT_RESTING_HEART_RATE = 53
    DERIVED_OVERNIGHT_HEART_METRICS = 54


class AnnotationType(Enum):
    """Annotation types."""
    UNKNOWN_ANNOTATION = 0
    ANNOTATION_WEARING = 1
    ANNOTATION_OUTDOOR = 2
    ANNOTATION_RESTING = 3
    ANNOTATION_ACTIVITY_INACTIVE = 4
    ANNOTATION_ACTIVITY_WALKING = 6
    ANNOTATION_ACTIVITY_BIKING = 25
    ANNOTATION_ACTIVITY_ACTIVE = 8
    ANNOTATION_ACTIVITY_AMBULATORY = 45
    ANNOTATION_ACTIVITY_OTHER_ACTIVE = 47
    ANNOTATION_PULSE_MAX = 9
    ANNOTATION_PULSE_MODERATE = 11
    ANNOTATION_RESPIRATION_RATE_PEAK = 12
    ANNOTATION_DAYLIGHT = 13
    ANNOTATION_UV_EXPOSURE = 14
    ANNOTATION_SLEEPING = 15
    ANNOTATION_IN_BED = 16
    ANNOTATION_AMBIENT_AUDIO_HIGH = 17
    ANNOTATION_AMBIENT_LIGHT_HIGH = 18
    ANNOTATION_BLUETOOTH_DEVICES_NEARBY = 19
    ANNOTATION_WIFI_NETWORKS_NEARBY = 20
    ANNOTATION_APP_RUNNING = 21
    ANNOTATION_APP_SENSORS_RUNNING = 39
    ANNOTATION_PHONE_PROXIMITY = 22
    ANNOTATION_ECG_TAKEN = 23
    ANNOTATION_ECG_SESSION = 40
    ANNOTATION_ACCEL_INTENSITY_HIGH = 26
    ANNOTATION_PHONE_SCREEN_ON = 27
    ANNOTATION_PHONE_SCREEN_ON_USER_PRESENT = 28
    ANNOTATION_PHONE_CHARGING_AC = 29
    ANNOTATION_PHONE_CHARGING_USB = 30
    ANNOTATION_PHONE_CHARGING = 31
    ANNOTATION_PHONE_CALL_ON_INCOMING = 32
    ANNOTATION_PHONE_CALL_ON_OUTGOING = 33
    ANNOTATION_PHONE_CALL_RINGING_UNTIL_MISSED_INCOMING = 34
    ANNOTATION_PHONE_CALL_RINGING_UNTIL_ANSWERED_INCOMING = 35
    ANNOTATION_PHONE_CALL_OUTGOING_INITIATED = 36
    ANNOTATION_PHONE_CALL_RINGING_AS_CALL_WAITING = 37
    ANNOTATION_PHONE_CALL_DIALED_OUTGOING_DURING_CALL = 38
    ANNOTATION_LOCATION_HOME = 41
    ANNOTATION_LOCATION_WORK = 42
    ANNOTATION_LOCATION_UNKNOWN = 43
    ANNOTATION_LOCATION_COMMUTE = 44
    ANNOTATION_PHONE_LOW_BATTERY = 48
    ANNOTATION_PHONE_MEDIUM_BATTERY = 49
    ANNOTATION_PHONE_HIGH_BATTERY = 50


@dataclasses.dataclass
class MetricType(object):
    stream_item_type: Optional[DeviceMeasurementType] = None
    derived_data_type: Optional[DerivedMetricType] = None
    annotation_type: Optional[AnnotationType] = None


@dataclasses.dataclass
class Version(object):
    name: Optional[str] = None
    number: Optional[int] = None


@dataclasses.dataclass
class Source(object):
    metric_type: Optional[MetricType] = None
    version: Optional[Version] = None
