"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
import verily.ds_sdk.protos.enums_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BluetoothFormatType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BluetoothFormatTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BluetoothFormatType.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSPECIFIED_FORMAT_TYPE: _BluetoothFormatType.ValueType  # 0
    """For unparsable data. Do not use."""
    FLOAT: _BluetoothFormatType.ValueType  # 1
    """32-bit float"""
    SFLOAT: _BluetoothFormatType.ValueType  # 2
    """16-bit float"""
    SINT32: _BluetoothFormatType.ValueType  # 3
    """Signed 32-bit integer"""
    SINT64: _BluetoothFormatType.ValueType  # 4
    """Signed 64-bit integer"""
    UINT8: _BluetoothFormatType.ValueType  # 5
    """Unsigned 8-bit byte"""
    UINT16: _BluetoothFormatType.ValueType  # 6
    """Unsigned 16-bit short"""
    UINT32: _BluetoothFormatType.ValueType  # 7
    """Unsigned 32-bit integer"""

class BluetoothFormatType(_BluetoothFormatType, metaclass=_BluetoothFormatTypeEnumTypeWrapper):
    """See: https://www.bluetooth.com/specifications/assigned-numbers/format-types"""

UNSPECIFIED_FORMAT_TYPE: BluetoothFormatType.ValueType  # 0
"""For unparsable data. Do not use."""
FLOAT: BluetoothFormatType.ValueType  # 1
"""32-bit float"""
SFLOAT: BluetoothFormatType.ValueType  # 2
"""16-bit float"""
SINT32: BluetoothFormatType.ValueType  # 3
"""Signed 32-bit integer"""
SINT64: BluetoothFormatType.ValueType  # 4
"""Signed 64-bit integer"""
UINT8: BluetoothFormatType.ValueType  # 5
"""Unsigned 8-bit byte"""
UINT16: BluetoothFormatType.ValueType  # 6
"""Unsigned 16-bit short"""
UINT32: BluetoothFormatType.ValueType  # 7
"""Unsigned 32-bit integer"""
global___BluetoothFormatType = BluetoothFormatType

class BlePeripheralDeviceConfig(google.protobuf.message.Message):
    """Configuration of a BLE peripheral sensor device."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEATURES_FIELD_NUMBER: builtins.int
    SCAN_SERVICE_UUID_FIELD_NUMBER: builtins.int
    MANUFACTURER_ID_FIELD_NUMBER: builtins.int
    @property
    def features(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BlePeripheralFeatureConfig]:
        """Features that the BLE peripheral provides."""
    scan_service_uuid: builtins.str
    """Service UUID to scan for when discovering devices of this type."""
    manufacturer_id: builtins.int
    """Manufacturer ID to filter by when discovering devices of this type."""
    def __init__(
        self,
        *,
        features: collections.abc.Iterable[global___BlePeripheralFeatureConfig] | None = ...,
        scan_service_uuid: builtins.str = ...,
        manufacturer_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["features", b"features", "manufacturer_id", b"manufacturer_id", "scan_service_uuid", b"scan_service_uuid"]) -> None: ...

global___BlePeripheralDeviceConfig = BlePeripheralDeviceConfig

class BlePeripheralFeatureConfig(google.protobuf.message.Message):
    """Configuration of a BLE feature of a peripheral sensor device."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READS_FIELD_NUMBER: builtins.int
    NOTIFICATIONS_FIELD_NUMBER: builtins.int
    @property
    def reads(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BlePeripheralCharacteristicConfig]:
        """The characteristics to read. May or may not be used to populate anything."""
    @property
    def notifications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BlePeripheralCharacteristicConfig]:
        """The characteristics to register for notifications about, after all reads
        are processed. May or may not be used to populate anything.
        """
    def __init__(
        self,
        *,
        reads: collections.abc.Iterable[global___BlePeripheralCharacteristicConfig] | None = ...,
        notifications: collections.abc.Iterable[global___BlePeripheralCharacteristicConfig] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["notifications", b"notifications", "reads", b"reads"]) -> None: ...

global___BlePeripheralFeatureConfig = BlePeripheralFeatureConfig

class BlePeripheralCharacteristicConfig(google.protobuf.message.Message):
    """Configuration of a BLE characteristic of a peripheral device."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_UUID_FIELD_NUMBER: builtins.int
    CHARACTERISTIC_UUID_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    service_uuid: builtins.str
    """Identifier of the BLE service that this characteristic is a part of."""
    characteristic_uuid: builtins.str
    """Identifier of the BLE characteristic."""
    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BlePeripheralFieldConfig]:
        """The fields to be read from the bytes returned for this characteristic,
        in the order that they should be read.
        Can be empty if this doesn’t populate anything.
        """
    def __init__(
        self,
        *,
        service_uuid: builtins.str = ...,
        characteristic_uuid: builtins.str = ...,
        fields: collections.abc.Iterable[global___BlePeripheralFieldConfig] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["characteristic_uuid", b"characteristic_uuid", "fields", b"fields", "service_uuid", b"service_uuid"]) -> None: ...

global___BlePeripheralCharacteristicConfig = BlePeripheralCharacteristicConfig

class BlePeripheralFieldConfig(google.protobuf.message.Message):
    """The field that is being populated. If this is "_TIMESTAMP",
    the field is the timestamp for the reading. If this is "_FLAGS",
    the field is the flags used to evaluate the rest of the reading.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELD_NAME_FIELD_NUMBER: builtins.int
    FLAGS_BITMASK_FIELD_NUMBER: builtins.int
    FLAGS_VALUE_FIELD_NUMBER: builtins.int
    FORMAT_TYPE_FIELD_NUMBER: builtins.int
    UNIT_TYPE_FIELD_NUMBER: builtins.int
    MULTIPLIER_FIELD_NUMBER: builtins.int
    ENUM_FIELDS_FIELD_NUMBER: builtins.int
    DATA_SPEC_NAME_FIELD_NUMBER: builtins.int
    field_name: builtins.str
    """Note that the same field name can be used multiple times, but should have
    different values for flag_bitmask each time that are mutually exclusive.
    """
    flags_bitmask: builtins.int
    """A bitmask that when ANDed with the flags for the characteristic must match
    flag_value in order for this field to be used.
    """
    flags_value: builtins.int
    """The value that the flags ANDed with flag_bitmask must match."""
    format_type: global___BluetoothFormatType.ValueType
    """The format of the value for this field in the data."""
    unit_type: verily.ds_sdk.protos.enums_pb2.UnitType.ValueType
    """The unit of measurement."""
    multiplier: builtins.float
    """Multiplier for values for this field. Combines multiplier and exponent
    from Bluetooth spec.
    """
    @property
    def enum_fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BleFlagEnumFieldConfig]:
        """If not empty, one or more enum fields are calculated based on the value
        of this field, based on the bits of the value of this field.
        These wind up in Datum.enum_values.
        """
    data_spec_name: builtins.str
    """The name of the Sensor Suite data spec that this field should be
    added as a data point for. If not set, this field will not populate
    a data point.
    """
    def __init__(
        self,
        *,
        field_name: builtins.str = ...,
        flags_bitmask: builtins.int = ...,
        flags_value: builtins.int = ...,
        format_type: global___BluetoothFormatType.ValueType = ...,
        unit_type: verily.ds_sdk.protos.enums_pb2.UnitType.ValueType = ...,
        multiplier: builtins.float = ...,
        enum_fields: collections.abc.Iterable[global___BleFlagEnumFieldConfig] | None = ...,
        data_spec_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data_spec_name", b"data_spec_name", "enum_fields", b"enum_fields", "field_name", b"field_name", "flags_bitmask", b"flags_bitmask", "flags_value", b"flags_value", "format_type", b"format_type", "multiplier", b"multiplier", "unit_type", b"unit_type"]) -> None: ...

global___BlePeripheralFieldConfig = BlePeripheralFieldConfig

class BleFlagEnumFieldConfig(google.protobuf.message.Message):
    """Bit-masked flag values for the measurement. Used in parsing packed BLE data.
    For example, whether or not a field value is packed or omitted from BLE data.
    For a concrete example see the "Flags" field in
    https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.blood_pressure_measurement.xml.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELD_NAME_FIELD_NUMBER: builtins.int
    NUM_BITS_FIELD_NUMBER: builtins.int
    VALUE_MAPPINGS_FIELD_NUMBER: builtins.int
    DATA_SPEC_NAME_FIELD_NUMBER: builtins.int
    field_name: builtins.str
    """The field name for the enum. If not set, this field will not be returned
    (we just skip past the bits.)
    """
    num_bits: builtins.int
    """The number of bits used to represent this enum from the value of the parent
    field.
    """
    @property
    def value_mappings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BleFlagEnumValueMapping]:
        """Mappings from flag values to names. If this is empty, the field name will
        use the numeric value of the bits; this is most useful for simple boolean
        flag fields.
        """
    data_spec_name: builtins.str
    """The name of the Sensor Suite data spec containing data points to populate
    with values from this enum. If not set, no data points will be populated.
    """
    def __init__(
        self,
        *,
        field_name: builtins.str = ...,
        num_bits: builtins.int = ...,
        value_mappings: collections.abc.Iterable[global___BleFlagEnumValueMapping] | None = ...,
        data_spec_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data_spec_name", b"data_spec_name", "field_name", b"field_name", "num_bits", b"num_bits", "value_mappings", b"value_mappings"]) -> None: ...

global___BleFlagEnumFieldConfig = BleFlagEnumFieldConfig

class BleFlagEnumValueMapping(google.protobuf.message.Message):
    """Mapping of flag value to names."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FLAGS_VALUE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    flags_value: builtins.int
    """A numeric value for a flag enum field."""
    name: builtins.str
    """The string value that the bit value maps to; this is what will be returned
    in the Datum for the field when the value for the bits matches flags_value.
    """
    def __init__(
        self,
        *,
        flags_value: builtins.int = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["flags_value", b"flags_value", "name", b"name"]) -> None: ...

global___BleFlagEnumValueMapping = BleFlagEnumValueMapping
