"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ApplicationId:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ApplicationIdEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ApplicationId.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    APPLICATION_ID_UNSPECIFIED: _ApplicationId.ValueType  # 0
    """For unparsable data. Do not use."""
    TESTING: _ApplicationId.ValueType  # 1
    """Can be used for testing purposes. Data stored as TESTING is not guaranteed
    to be kept forever.
    """
    STUDY_KIT: _ApplicationId.ValueType  # 2
    """Study Kit is a health tracking device created by the Verily Life Sciences
    team. The device gathers and understands data about a patient's health and
    can aid in early disease detection for those with cardiovascular and
    movement disorders.
    (-- go/studykit --)
    """
    MYALO: _ApplicationId.ValueType  # 3
    """Myalo is a clinical study run by Verily Life Sciences."""
    BASELINE: _ApplicationId.ValueType  # 4
    """Baseline is a clinical study run by Verily Life Sciences."""

class ApplicationId(_ApplicationId, metaclass=_ApplicationIdEnumTypeWrapper):
    """LINT.IfChange
    All data is segmented by the Verily application which created it.
    """

APPLICATION_ID_UNSPECIFIED: ApplicationId.ValueType  # 0
"""For unparsable data. Do not use."""
TESTING: ApplicationId.ValueType  # 1
"""Can be used for testing purposes. Data stored as TESTING is not guaranteed
to be kept forever.
"""
STUDY_KIT: ApplicationId.ValueType  # 2
"""Study Kit is a health tracking device created by the Verily Life Sciences
team. The device gathers and understands data about a patient's health and
can aid in early disease detection for those with cardiovascular and
movement disorders.
(-- go/studykit --)
"""
MYALO: ApplicationId.ValueType  # 3
"""Myalo is a clinical study run by Verily Life Sciences."""
BASELINE: ApplicationId.ValueType  # 4
"""Baseline is a clinical study run by Verily Life Sciences."""
global___ApplicationId = ApplicationId

class _UserIdKeyspace:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UserIdKeyspaceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UserIdKeyspace.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    USER_ID_KEYSPACE_UNSPECIFIED: _UserIdKeyspace.ValueType  # 0
    """For unparsable data. Do not use."""
    GAIA_ID: _UserIdKeyspace.ValueType  # 1
    """UserId is a GAIA ID, see:
    https://developers.google.com/issue-tracker/concepts/access-control#users
    """
    HASHED_STRING: _UserIdKeyspace.ValueType  # 2
    """See UserId.user_string."""
    CSP_ID: _UserIdKeyspace.ValueType  # 3
    """UserId is a CSP ID. Uses UserId.user_string.
    TODO(b/180118973): If used for ReadDataPoints, this is always the external
    CSP ID. This is the internal CSP ID for the SensorStore storage.
    """
    ANON_STUDY_DEVICE: _UserIdKeyspace.ValueType  # 4
    """UserId is for an anonymous study device. Uses UserId.user_string."""
    SENSOR_REGISTRY_CUSTOM: _UserIdKeyspace.ValueType  # 5
    """Custom identifier from sensor registry. Uses UserId.user_string."""
    DMI: _UserIdKeyspace.ValueType  # 6
    """Users in the DMI system. Uses Userid.user_string. Caller must be
    authenticated with the DMI system.
    """
    CSP_UUID: _UserIdKeyspace.ValueType  # 7
    """UserId is a CSP study participant ID currently used in the China version of
    the Baseline platform version. Uses UserId.user_string.
    """
    FIREBASE: _UserIdKeyspace.ValueType  # 8
    """Firebase accounts user ID. Uses Userid.user_string."""
    CSP_INTERNAL_ID: _UserIdKeyspace.ValueType  # 9
    """UserId is a CSP Internal ID. Uses UserId.user_string."""

class UserIdKeyspace(_UserIdKeyspace, metaclass=_UserIdKeyspaceEnumTypeWrapper):
    """Keyspace the UserId is in."""

USER_ID_KEYSPACE_UNSPECIFIED: UserIdKeyspace.ValueType  # 0
"""For unparsable data. Do not use."""
GAIA_ID: UserIdKeyspace.ValueType  # 1
"""UserId is a GAIA ID, see:
https://developers.google.com/issue-tracker/concepts/access-control#users
"""
HASHED_STRING: UserIdKeyspace.ValueType  # 2
"""See UserId.user_string."""
CSP_ID: UserIdKeyspace.ValueType  # 3
"""UserId is a CSP ID. Uses UserId.user_string.
TODO(b/180118973): If used for ReadDataPoints, this is always the external
CSP ID. This is the internal CSP ID for the SensorStore storage.
"""
ANON_STUDY_DEVICE: UserIdKeyspace.ValueType  # 4
"""UserId is for an anonymous study device. Uses UserId.user_string."""
SENSOR_REGISTRY_CUSTOM: UserIdKeyspace.ValueType  # 5
"""Custom identifier from sensor registry. Uses UserId.user_string."""
DMI: UserIdKeyspace.ValueType  # 6
"""Users in the DMI system. Uses Userid.user_string. Caller must be
authenticated with the DMI system.
"""
CSP_UUID: UserIdKeyspace.ValueType  # 7
"""UserId is a CSP study participant ID currently used in the China version of
the Baseline platform version. Uses UserId.user_string.
"""
FIREBASE: UserIdKeyspace.ValueType  # 8
"""Firebase accounts user ID. Uses Userid.user_string."""
CSP_INTERNAL_ID: UserIdKeyspace.ValueType  # 9
"""UserId is a CSP Internal ID. Uses UserId.user_string."""
global___UserIdKeyspace = UserIdKeyspace

class _PrimitiveType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PrimitiveTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PrimitiveType.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRIMITIVE_TYPE_UNSPECIFIED: _PrimitiveType.ValueType  # 0
    """For unparsable data. Do not use."""
    INT64: _PrimitiveType.ValueType  # 1
    """A single int64."""
    INT64_LIST: _PrimitiveType.ValueType  # 2
    """A list of int64s."""
    FLOAT64: _PrimitiveType.ValueType  # 3
    """A single float64."""
    FLOAT64_LIST: _PrimitiveType.ValueType  # 4
    """A list of float64s."""
    STRING: _PrimitiveType.ValueType  # 5
    """A single string."""
    STRING_LIST: _PrimitiveType.ValueType  # 6
    """A list of string."""
    BLOB: _PrimitiveType.ValueType  # 7
    """A blob of bytes."""
    ANY: _PrimitiveType.ValueType  # 8
    """An Any message."""
    BOOLEAN: _PrimitiveType.ValueType  # 9
    """A single boolean."""
    BOOLEAN_LIST: _PrimitiveType.ValueType  # 10
    """A list of booleans."""
    BLOB_LIST: _PrimitiveType.ValueType  # 11
    """A list of blobs."""

class PrimitiveType(_PrimitiveType, metaclass=_PrimitiveTypeEnumTypeWrapper):
    """This must be kept in sync with the Value.data oneof. See comments in Value."""

PRIMITIVE_TYPE_UNSPECIFIED: PrimitiveType.ValueType  # 0
"""For unparsable data. Do not use."""
INT64: PrimitiveType.ValueType  # 1
"""A single int64."""
INT64_LIST: PrimitiveType.ValueType  # 2
"""A list of int64s."""
FLOAT64: PrimitiveType.ValueType  # 3
"""A single float64."""
FLOAT64_LIST: PrimitiveType.ValueType  # 4
"""A list of float64s."""
STRING: PrimitiveType.ValueType  # 5
"""A single string."""
STRING_LIST: PrimitiveType.ValueType  # 6
"""A list of string."""
BLOB: PrimitiveType.ValueType  # 7
"""A blob of bytes."""
ANY: PrimitiveType.ValueType  # 8
"""An Any message."""
BOOLEAN: PrimitiveType.ValueType  # 9
"""A single boolean."""
BOOLEAN_LIST: PrimitiveType.ValueType  # 10
"""A list of booleans."""
BLOB_LIST: PrimitiveType.ValueType  # 11
"""A list of blobs."""
global___PrimitiveType = PrimitiveType

class _UnitType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UnitTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UnitType.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNIT_TYPE_UNSPECIFIED: _UnitType.ValueType  # 0
    """For unparsable data. Do not use."""
    COUNT: _UnitType.ValueType  # 1
    """Special unit to indicate some counting metric (unitless)."""
    RATIO: _UnitType.ValueType  # 2
    """Special unit to indicate a ratio (unitless)."""
    METER: _UnitType.ValueType  # 3
    """Unit of length."""
    GRAM: _UnitType.ValueType  # 4
    """Unit of mass."""
    SECOND: _UnitType.ValueType  # 5
    """Unit of time."""
    AMPERE: _UnitType.ValueType  # 6
    """Unit of electric current."""
    KELVIN: _UnitType.ValueType  # 7
    """Unit of thermodynamic temperature."""
    MOLE: _UnitType.ValueType  # 8
    """Unit of amount of substance."""
    CANDELA: _UnitType.ValueType  # 9
    """Unit of luminous intensity."""
    PERCENT: _UnitType.ValueType  # 10
    """Derived special unit. HECTO * RATIO"""
    LITER: _UnitType.ValueType  # 11
    """Derived unit of volume. MILLI * METER^3"""
    VOLT: _UnitType.ValueType  # 12
    """Derived unit of electrical potential difference.
    (KILO * GRAM) * METER^2 * AMPERE^-1 * SECOND^-3
    """
    PASCAL: _UnitType.ValueType  # 13
    """Derived unit of pressure or stress.
    (KILO * GRAM) * METER^-1 * SECOND^-2
    """
    NEWTON: _UnitType.ValueType  # 14
    """Derived unit of force.
    (KILO * GRAM) * METER * SECOND^-2
    """
    JOULE: _UnitType.ValueType  # 15
    """Derived unit of energy, work or heat.
    (KILO * GRAM) * METER^2 * SECOND^-2
    """
    RADIAN: _UnitType.ValueType  # 16
    """Derived unit of angle."""
    DEGREE: _UnitType.ValueType  # 17
    """Derived unit of angle. π / 180 * RADIAN"""
    STERADIAN: _UnitType.ValueType  # 18
    """Derived unit of solid angle."""
    CELSIUS: _UnitType.ValueType  # 19
    """Derived unit of temperature. KELVIN - 273.15"""
    VELOCITY: _UnitType.ValueType  # 20
    """Derived unit. METER * SECOND^-1"""
    ACCELERATION: _UnitType.ValueType  # 21
    """Derived unit. METER * SECOND^-2"""
    LUMEN: _UnitType.ValueType  # 22
    """Derived unit of luminous flux. CANDELA * STERADIAN"""
    LUX: _UnitType.ValueType  # 23
    """Derived unit of illuminance. LUMEN * METER^-2"""
    OHM: _UnitType.ValueType  # 24
    """Derived unit of electrical resistance. VOLT * AMPERE^-1"""
    WATT: _UnitType.ValueType  # 25
    """Derived unit of power. JOULE * SECOND^-1."""
    BIT: _UnitType.ValueType  # 26
    """Unit of information."""
    BYTE: _UnitType.ValueType  # 27
    """Derived unit of information. 8 * BIT"""
    TESLA: _UnitType.ValueType  # 28
    """Derived unit. NEWTON / (AMPERE * METER)"""
    MMHG: _UnitType.ValueType  # 29
    """Derived unit of pressure or stress. 133.322387415 * PASCAL"""
    CMH2O: _UnitType.ValueType  # 30
    """Derived unit of pressure or stress. 0.0101972 * PASCAL"""
    MINUTE: _UnitType.ValueType  # 31
    """Derived unit of time. 60 * SECOND"""
    HOUR: _UnitType.ValueType  # 32
    """Derived unit of time. 3600 * SECOND"""

class UnitType(_UnitType, metaclass=_UnitTypeEnumTypeWrapper):
    """This enum is for all core standard physical units, plus a few derived ones
    for convenience. See:
    http://physics.nist.gov/cuu/Units/units.html
    """

UNIT_TYPE_UNSPECIFIED: UnitType.ValueType  # 0
"""For unparsable data. Do not use."""
COUNT: UnitType.ValueType  # 1
"""Special unit to indicate some counting metric (unitless)."""
RATIO: UnitType.ValueType  # 2
"""Special unit to indicate a ratio (unitless)."""
METER: UnitType.ValueType  # 3
"""Unit of length."""
GRAM: UnitType.ValueType  # 4
"""Unit of mass."""
SECOND: UnitType.ValueType  # 5
"""Unit of time."""
AMPERE: UnitType.ValueType  # 6
"""Unit of electric current."""
KELVIN: UnitType.ValueType  # 7
"""Unit of thermodynamic temperature."""
MOLE: UnitType.ValueType  # 8
"""Unit of amount of substance."""
CANDELA: UnitType.ValueType  # 9
"""Unit of luminous intensity."""
PERCENT: UnitType.ValueType  # 10
"""Derived special unit. HECTO * RATIO"""
LITER: UnitType.ValueType  # 11
"""Derived unit of volume. MILLI * METER^3"""
VOLT: UnitType.ValueType  # 12
"""Derived unit of electrical potential difference.
(KILO * GRAM) * METER^2 * AMPERE^-1 * SECOND^-3
"""
PASCAL: UnitType.ValueType  # 13
"""Derived unit of pressure or stress.
(KILO * GRAM) * METER^-1 * SECOND^-2
"""
NEWTON: UnitType.ValueType  # 14
"""Derived unit of force.
(KILO * GRAM) * METER * SECOND^-2
"""
JOULE: UnitType.ValueType  # 15
"""Derived unit of energy, work or heat.
(KILO * GRAM) * METER^2 * SECOND^-2
"""
RADIAN: UnitType.ValueType  # 16
"""Derived unit of angle."""
DEGREE: UnitType.ValueType  # 17
"""Derived unit of angle. π / 180 * RADIAN"""
STERADIAN: UnitType.ValueType  # 18
"""Derived unit of solid angle."""
CELSIUS: UnitType.ValueType  # 19
"""Derived unit of temperature. KELVIN - 273.15"""
VELOCITY: UnitType.ValueType  # 20
"""Derived unit. METER * SECOND^-1"""
ACCELERATION: UnitType.ValueType  # 21
"""Derived unit. METER * SECOND^-2"""
LUMEN: UnitType.ValueType  # 22
"""Derived unit of luminous flux. CANDELA * STERADIAN"""
LUX: UnitType.ValueType  # 23
"""Derived unit of illuminance. LUMEN * METER^-2"""
OHM: UnitType.ValueType  # 24
"""Derived unit of electrical resistance. VOLT * AMPERE^-1"""
WATT: UnitType.ValueType  # 25
"""Derived unit of power. JOULE * SECOND^-1."""
BIT: UnitType.ValueType  # 26
"""Unit of information."""
BYTE: UnitType.ValueType  # 27
"""Derived unit of information. 8 * BIT"""
TESLA: UnitType.ValueType  # 28
"""Derived unit. NEWTON / (AMPERE * METER)"""
MMHG: UnitType.ValueType  # 29
"""Derived unit of pressure or stress. 133.322387415 * PASCAL"""
CMH2O: UnitType.ValueType  # 30
"""Derived unit of pressure or stress. 0.0101972 * PASCAL"""
MINUTE: UnitType.ValueType  # 31
"""Derived unit of time. 60 * SECOND"""
HOUR: UnitType.ValueType  # 32
"""Derived unit of time. 3600 * SECOND"""
global___UnitType = UnitType

class _UnitScale:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UnitScaleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UnitScale.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNIT_SCALE_UNSPECIFIED: _UnitScale.ValueType  # 0
    """For unparsable data. Do not use."""
    UNIT: _UnitScale.ValueType  # 1
    """No scaling."""
    DECI: _UnitScale.ValueType  # 2
    """10^-1"""
    CENTI: _UnitScale.ValueType  # 3
    """10^-2"""
    MILLI: _UnitScale.ValueType  # 4
    """10^-3"""
    MICRO: _UnitScale.ValueType  # 5
    """10^-6"""
    NANO: _UnitScale.ValueType  # 6
    """10^-9"""
    PICO: _UnitScale.ValueType  # 7
    """10^-12"""
    FEMTO: _UnitScale.ValueType  # 8
    """10^-15"""
    DEKA: _UnitScale.ValueType  # 9
    """10^1"""
    HECTO: _UnitScale.ValueType  # 10
    """10^2"""
    KILO: _UnitScale.ValueType  # 11
    """10^3"""
    MEGA: _UnitScale.ValueType  # 12
    """10^6"""
    GIGA: _UnitScale.ValueType  # 13
    """10^9"""
    TERA: _UnitScale.ValueType  # 14
    """10^12"""
    PETA: _UnitScale.ValueType  # 15
    """10^15"""

class UnitScale(_UnitScale, metaclass=_UnitScaleEnumTypeWrapper):
    """Various scaling factors used throughout science. See:
    http://physics.nist.gov/cuu/Units/prefixes.html
    """

UNIT_SCALE_UNSPECIFIED: UnitScale.ValueType  # 0
"""For unparsable data. Do not use."""
UNIT: UnitScale.ValueType  # 1
"""No scaling."""
DECI: UnitScale.ValueType  # 2
"""10^-1"""
CENTI: UnitScale.ValueType  # 3
"""10^-2"""
MILLI: UnitScale.ValueType  # 4
"""10^-3"""
MICRO: UnitScale.ValueType  # 5
"""10^-6"""
NANO: UnitScale.ValueType  # 6
"""10^-9"""
PICO: UnitScale.ValueType  # 7
"""10^-12"""
FEMTO: UnitScale.ValueType  # 8
"""10^-15"""
DEKA: UnitScale.ValueType  # 9
"""10^1"""
HECTO: UnitScale.ValueType  # 10
"""10^2"""
KILO: UnitScale.ValueType  # 11
"""10^3"""
MEGA: UnitScale.ValueType  # 12
"""10^6"""
GIGA: UnitScale.ValueType  # 13
"""10^9"""
TERA: UnitScale.ValueType  # 14
"""10^12"""
PETA: UnitScale.ValueType  # 15
"""10^15"""
global___UnitScale = UnitScale

class _DaylightSavingTime:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DaylightSavingTimeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DaylightSavingTime.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DAYLIGHT_SAVING_TIME_UNSPECIFIED: _DaylightSavingTime.ValueType  # 0
    """The DST time is not specified, usually when the timezone is location-based."""
    STANDARD: _DaylightSavingTime.ValueType  # 1
    """The data is not measured with the DST time."""
    DST: _DaylightSavingTime.ValueType  # 2
    """The data is measured with the DST time."""

class DaylightSavingTime(_DaylightSavingTime, metaclass=_DaylightSavingTimeEnumTypeWrapper):
    """Whether the collected data is measured when the DST time is enabled."""

DAYLIGHT_SAVING_TIME_UNSPECIFIED: DaylightSavingTime.ValueType  # 0
"""The DST time is not specified, usually when the timezone is location-based."""
STANDARD: DaylightSavingTime.ValueType  # 1
"""The data is not measured with the DST time."""
DST: DaylightSavingTime.ValueType  # 2
"""The data is measured with the DST time."""
global___DaylightSavingTime = DaylightSavingTime
