"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import verily.ds_sdk.protos.management_resources_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ListRegistriesRequest(google.protobuf.message.Message):
    """Registries

    Request for the ListRegistries method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListRegistriesRequest = ListRegistriesRequest

class ListRegistriesResponse(google.protobuf.message.Message):
    """Response of the ListRegistries method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REGISTRIES_FIELD_NUMBER: builtins.int
    @property
    def registries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[verily.ds_sdk.protos.management_resources_pb2.Registry]:
        """Registries that the caller has at least `VIEWER` access to."""
    def __init__(
        self,
        *,
        registries: collections.abc.Iterable[verily.ds_sdk.protos.management_resources_pb2.Registry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["registries", b"registries"]) -> None: ...

global___ListRegistriesResponse = ListRegistriesResponse
