"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.rpc.status_pb2
import sys
import typing
import verily.ds_sdk.protos.ble_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DataStorageLocation:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DataStorageLocationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DataStorageLocation.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DATA_STORAGE_LOCATION_UNSPECIFIED: _DataStorageLocation.ValueType  # 0
    """Reserved."""
    DATA_STORAGE_LOCATION_US: _DataStorageLocation.ValueType  # 1
    """Sensor data is stored in US-only Spanner allocs and exports in the 'US' GCP
    location, see: https://cloud.google.com/bigquery/docs/locations.
    """
    DATA_STORAGE_LOCATION_EU: _DataStorageLocation.ValueType  # 2
    """Sensor data is stored in EU-only Spanner allocs and exports in the EU GCP
    location.
    """

class DataStorageLocation(_DataStorageLocation, metaclass=_DataStorageLocationEnumTypeWrapper):
    """The location where data will be stored."""

DATA_STORAGE_LOCATION_UNSPECIFIED: DataStorageLocation.ValueType  # 0
"""Reserved."""
DATA_STORAGE_LOCATION_US: DataStorageLocation.ValueType  # 1
"""Sensor data is stored in US-only Spanner allocs and exports in the 'US' GCP
location, see: https://cloud.google.com/bigquery/docs/locations.
"""
DATA_STORAGE_LOCATION_EU: DataStorageLocation.ValueType  # 2
"""Sensor data is stored in EU-only Spanner allocs and exports in the EU GCP
location.
"""
global___DataStorageLocation = DataStorageLocation

class Registry(google.protobuf.message.Message):
    """A registry is a grouping of devices that are associated with a common ACL.
    When a device is created it must be created within an existing registry.
    Registries can be arbitrarily created by clients. In practice, the concept of
    Registry aligns with a set of devices intended to be used by a large study
    (e.g. Baseline).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    CREATION_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    POLICY_FIELD_NUMBER: builtins.int
    STUDY_ID_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of this Registry in the format
    "registries/<Registry GUID>".
    E.g. "registries/e3bc11dc-1a06-06d7-5bab-ffd8e884fe59".
    """
    display_name: builtins.str
    """Display-friendly name of this Registry."""
    creation_time: builtins.int
    """Output only. In milliseconds since UNIX epoch."""
    update_time: builtins.int
    """Output only. In milliseconds since UNIX epoch."""
    @property
    def policy(self) -> global___RegistryPolicy:
        """Policy to control custom behavior for this Registry."""
    study_id: builtins.str
    """The resource name of the study that this registry is associated with."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        display_name: builtins.str = ...,
        creation_time: builtins.int = ...,
        update_time: builtins.int = ...,
        policy: global___RegistryPolicy | None = ...,
        study_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["policy", b"policy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["creation_time", b"creation_time", "display_name", b"display_name", "name", b"name", "policy", b"policy", "study_id", b"study_id", "update_time", b"update_time"]) -> None: ...

global___Registry = Registry

class RegistryPolicy(google.protobuf.message.Message):
    """RegistryPolicy allows registries to enforce certain behaviors e.g. all
    participants must be in FOO namespace.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class DeviceSpecDefaultDeviceConfigsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___DeviceConfig: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___DeviceConfig | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    REQUIRED_PARTICIPANT_NAMESPACE_FIELD_NUMBER: builtins.int
    LEGACY_ANONYMOUS_STUDY_PREFIX_FIELD_NUMBER: builtins.int
    DEVICE_SPECS_FIELD_NUMBER: builtins.int
    TOPIC_CONFIGS_FIELD_NUMBER: builtins.int
    FIREBASE_PROJECT_ID_FIELD_NUMBER: builtins.int
    ENABLE_PARTICIPANT_SERVICE_FIELD_NUMBER: builtins.int
    ALLOWED_AUTHORITIES_FIELD_NUMBER: builtins.int
    DEVICE_SPEC_DEFAULT_DEVICE_CONFIGS_FIELD_NUMBER: builtins.int
    DATA_STORAGE_LOCATION_FIELD_NUMBER: builtins.int
    DATA_EXPORT_CONFIGS_FIELD_NUMBER: builtins.int
    DELEGATION_4D_ONLY_FIELD_NUMBER: builtins.int
    AUTHORIZATION_DELEGATES_FIELD_NUMBER: builtins.int
    required_participant_namespace: global___Participant.ParticipantNamespace.ValueType
    """If set, all participants created/updated in this registry must belong to
    this namespace.
    """
    legacy_anonymous_study_prefix: builtins.str
    """When required_participant_namespace is ANON_STUDY_DEVICE, this prefix must
    be non-empty, and all subsequent participant creation and updates will
    verify that the participant id contains this prefix.
    """
    @property
    def device_specs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Whitelist of DeviceSpecs required by this Registry. Devices created without
        a whitelisted DeviceSpec will be rejected. If the list is empty, then no
        DeviceSpec is required and any DeviceSpec can be used. Field values are
        DeviceSpec names. E.g. "deviceSpecs/com.verily.study_watch".
        """
    @property
    def topic_configs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TopicConfig]:
        """The description of how SensorStore publishes to the Cloud Pub/Sub Service
        for notifications about when a device in this registry uploads data.
        """
    firebase_project_id: builtins.str
    """The Firebase project ID that is used for all the participant with FIREBASE
    namespace in this Registry.
    """
    enable_participant_service: builtins.bool
    """Whether to enable ParticipantService, which allows participants to
    create/delete their claimed devices. `device_specs` must not be empty if
    this is set to true.
    """
    @property
    def allowed_authorities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeviceAuthority]:
        """Principals that are allowed authorities for the authorization of device
        requests in the registry.
        """
    @property
    def device_spec_default_device_configs(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___DeviceConfig]:
        """Mapping of device specs to default device configurations."""
    data_storage_location: global___DataStorageLocation.ValueType
    """Determines where sensor data for this registry is stored. This governs both
    the location of the Spanner servers which hold a consistent storage of
    data, as well the location for the BigQuery dataset, if BigQuery exports
    are enabled. The intermediate GCS bucket location must also be compatible
    with this location. See https://cloud.google.com/bigquery/docs/locations.
    """
    @property
    def data_export_configs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DataExportConfig]:
        """Configuration for exporting SensorStore device data to BigQuery, with
        writing Avro files to GCS as an intermediary.
        """
    delegation_4d_only: builtins.bool
    """Whether the SensorStore delegation of this Registry only takes place in the
    flattened Spanner schema, see go/sensorsuite-delegation-4d. Deprecated.
    """
    @property
    def authorization_delegates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AuthorizationDelegate]:
        """The authorization backends to use."""
    def __init__(
        self,
        *,
        required_participant_namespace: global___Participant.ParticipantNamespace.ValueType = ...,
        legacy_anonymous_study_prefix: builtins.str = ...,
        device_specs: collections.abc.Iterable[builtins.str] | None = ...,
        topic_configs: collections.abc.Iterable[global___TopicConfig] | None = ...,
        firebase_project_id: builtins.str = ...,
        enable_participant_service: builtins.bool = ...,
        allowed_authorities: collections.abc.Iterable[global___DeviceAuthority] | None = ...,
        device_spec_default_device_configs: collections.abc.Mapping[builtins.str, global___DeviceConfig] | None = ...,
        data_storage_location: global___DataStorageLocation.ValueType = ...,
        data_export_configs: collections.abc.Iterable[global___DataExportConfig] | None = ...,
        delegation_4d_only: builtins.bool = ...,
        authorization_delegates: collections.abc.Iterable[global___AuthorizationDelegate] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["allowed_authorities", b"allowed_authorities", "authorization_delegates", b"authorization_delegates", "data_export_configs", b"data_export_configs", "data_storage_location", b"data_storage_location", "delegation_4d_only", b"delegation_4d_only", "device_spec_default_device_configs", b"device_spec_default_device_configs", "device_specs", b"device_specs", "enable_participant_service", b"enable_participant_service", "firebase_project_id", b"firebase_project_id", "legacy_anonymous_study_prefix", b"legacy_anonymous_study_prefix", "required_participant_namespace", b"required_participant_namespace", "topic_configs", b"topic_configs"]) -> None: ...

global___RegistryPolicy = RegistryPolicy

class TopicConfig(google.protobuf.message.Message):
    """The description of how SensorStore publishes to the Cloud Pub/Sub Service
    for notifications about when a device uploads data. TopicConfigs are
    configured in a Registry's RegistryPolicy.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DATA_SPECS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of topic. e.g. "projects/myproject/topics/mytopic"."""
    @property
    def data_specs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of DataSpecs IDs to publish on this topic. DataSpecs are defined in
        SensorStore.
        """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        data_specs: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data_specs", b"data_specs", "name", b"name"]) -> None: ...

global___TopicConfig = TopicConfig

class DeviceConfig(google.protobuf.message.Message):
    """A Configuration represents the configuration of a device as intended by the
    service. Configuration flows one-way from cloud to device. A configuration's
    format is unknown to the Sensor Registry and is stored as an opaque binary.
    Note that the configuration of a device may differ from device to device even
    within the same Registry.

    LINT.IfChange(device_config)
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class DeviceHostConfig(google.protobuf.message.Message):
        """Host device connection information."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class BleConnection(google.protobuf.message.Message):
            """Defines the information necessary for creating a secure BLE connection
            to BLE peripherals (e.g. EarlySense).
            """

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            DEVICE_ID_FIELD_NUMBER: builtins.int
            MAC_ADDRESS_FIELD_NUMBER: builtins.int
            PASSKEY_FIELD_NUMBER: builtins.int
            CONFIG_FIELD_NUMBER: builtins.int
            device_id: builtins.str
            """The cross-registry unique identifier of this device. Same as
            `Device.global_id`.
            """
            mac_address: builtins.str
            """Required. MAC address of the BLE device."""
            passkey: builtins.int
            """Optional. Passkey for pairing with the BLE device; an integer between
            0-999999 per `chrome.bluetoothPrivate` API.
            See:
            http://cs.chromium.org/chromium/src/extensions/common/api/bluetooth_private.idl
            """
            @property
            def config(self) -> verily.ds_sdk.protos.ble_pb2.BlePeripheralDeviceConfig:
                """The BLE device configuration of the peripheral. This field is
                used by hosts to connect to implementation-agnostic BLE peripherals.
                Hosts can use the information in the peripheral's configuration to
                connect and parse data coming from the peripheral.
                """
            def __init__(
                self,
                *,
                device_id: builtins.str = ...,
                mac_address: builtins.str = ...,
                passkey: builtins.int = ...,
                config: verily.ds_sdk.protos.ble_pb2.BlePeripheralDeviceConfig | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["config", b"config"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "device_id", b"device_id", "mac_address", b"mac_address", "passkey", b"passkey"]) -> None: ...

        BLE_CONNECTIONS_FIELD_NUMBER: builtins.int
        @property
        def ble_connections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeviceConfig.DeviceHostConfig.BleConnection]:
            """List of all BLE connections supported by this host device."""
        def __init__(
            self,
            *,
            ble_connections: collections.abc.Iterable[global___DeviceConfig.DeviceHostConfig.BleConnection] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["ble_connections", b"ble_connections"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    ACK_TIME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    FIRMWARE_VERSION_FIELD_NUMBER: builtins.int
    FIRMWARE_URL_FIELD_NUMBER: builtins.int
    HOST_CONFIG_FIELD_NUMBER: builtins.int
    CONFIG_STATUS_FIELD_NUMBER: builtins.int
    SOURCE_DEVICE_CONFIG_SPEC_FIELD_NUMBER: builtins.int
    GROUP_DATA_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The resource name of this configuration. E.g.
    `"registries/xyz/devices/abc/configurations/3"`.
    """
    version: builtins.int
    """Integer version of the configuration. This value is generated by the server
    and is monotonically increasing.
    """
    create_time: builtins.int
    """Output only. In milliseconds since UNIX epoch."""
    ack_time: builtins.int
    """Output only. The time at which the device first acknowledged the
    application of the DeviceConfig. In milliseconds since UNIX epoch.
    """
    data: builtins.bytes
    """Blackbox data set by client. In practice, this field is set to a serialized
    protobuf controlled by client.
    """
    firmware_version: builtins.str
    """Firmware version that the device should be configured to."""
    firmware_url: builtins.str
    """Firmware url that the device should be configured to. In practice, this
    should be updated at the same time firmware_version is updated.
    """
    @property
    def host_config(self) -> global___DeviceConfig.DeviceHostConfig:
        """Defines connections supported by this host device. This field is only
        present for devices that are marked as device hosts. The field is
        read-only.
        """
    @property
    def config_status(self) -> google.rpc.status_pb2.Status:
        """The status of the device applying this configuration. Status = OK is
        assumed if this field is not specified.
        """
    source_device_config_spec: builtins.str
    """Optional. Defines the resource id in the DeviceConfigSpecService this
    device configuration originated.
    """
    group_data: builtins.bytes
    """Blackbox data set by the DeviceGroup. This field is usually set to a
    serialized protobuf controlled by the client. The merging of `group_data`
    field and `data` field is controlled by other services.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.int = ...,
        create_time: builtins.int = ...,
        ack_time: builtins.int = ...,
        data: builtins.bytes = ...,
        firmware_version: builtins.str = ...,
        firmware_url: builtins.str = ...,
        host_config: global___DeviceConfig.DeviceHostConfig | None = ...,
        config_status: google.rpc.status_pb2.Status | None = ...,
        source_device_config_spec: builtins.str = ...,
        group_data: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["config_status", b"config_status", "host_config", b"host_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ack_time", b"ack_time", "config_status", b"config_status", "create_time", b"create_time", "data", b"data", "firmware_url", b"firmware_url", "firmware_version", b"firmware_version", "group_data", b"group_data", "host_config", b"host_config", "name", b"name", "source_device_config_spec", b"source_device_config_spec", "version", b"version"]) -> None: ...

global___DeviceConfig = DeviceConfig

class DeviceAuthority(google.protobuf.message.Message):
    """An entity or principal that is the source of a device request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GAIA_FIELD_NUMBER: builtins.int
    LEGACY_FIELD_NUMBER: builtins.int
    ASYM_KEY_HOLDER_FIELD_NUMBER: builtins.int
    OBFUSCATED_GAIA_FIELD_NUMBER: builtins.int
    DELEGATED_ASYM_KEY_HOLDER_FIELD_NUMBER: builtins.int
    CURRENT_PARTICIPANT_FIELD_NUMBER: builtins.int
    @property
    def gaia(self) -> global___GaiaAuthority:
        """Info about a GAIA device authority."""
    @property
    def legacy(self) -> global___LegacyRialtoAppAuthority:
        """Info about a legacy Rialto app device authority."""
    @property
    def asym_key_holder(self) -> global___AsymKeyHolderAuthority:
        """Info about an asymmetric key holder device authority."""
    @property
    def obfuscated_gaia(self) -> global___ObfuscatedGaiaAuthority:
        """Info about an obfuscated GAIA device authority."""
    @property
    def delegated_asym_key_holder(self) -> global___AsymKeyHolderAuthority:
        """Info about an asymmetric key holder peripheral device authority."""
    @property
    def current_participant(self) -> global___CurrentParticipantAuthority:
        """Info about a current participant authority."""
    def __init__(
        self,
        *,
        gaia: global___GaiaAuthority | None = ...,
        legacy: global___LegacyRialtoAppAuthority | None = ...,
        asym_key_holder: global___AsymKeyHolderAuthority | None = ...,
        obfuscated_gaia: global___ObfuscatedGaiaAuthority | None = ...,
        delegated_asym_key_holder: global___AsymKeyHolderAuthority | None = ...,
        current_participant: global___CurrentParticipantAuthority | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asym_key_holder", b"asym_key_holder", "authority", b"authority", "current_participant", b"current_participant", "delegated_asym_key_holder", b"delegated_asym_key_holder", "gaia", b"gaia", "legacy", b"legacy", "obfuscated_gaia", b"obfuscated_gaia"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asym_key_holder", b"asym_key_holder", "authority", b"authority", "current_participant", b"current_participant", "delegated_asym_key_holder", b"delegated_asym_key_holder", "gaia", b"gaia", "legacy", b"legacy", "obfuscated_gaia", b"obfuscated_gaia"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["authority", b"authority"]) -> typing_extensions.Literal["gaia", "legacy", "asym_key_holder", "obfuscated_gaia", "delegated_asym_key_holder", "current_participant"] | None: ...

global___DeviceAuthority = DeviceAuthority

class GaiaAuthority(google.protobuf.message.Message):
    """The authority of a GAIA user/service account. Authentication is performed
    with OAuth2 or GaiaMint.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    email: builtins.str
    """A GAIA user is identified by its email address. This is mutually
    exclusive with `id`, so exactly one can be provided.
    """
    id: builtins.int
    """A GAIA user is also identified by its numeric GAIA ID. This is mutually
    exclusive with `email`, so exactly one can be provided.
    """
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email", "id", b"id"]) -> None: ...

global___GaiaAuthority = GaiaAuthority

class ObfuscatedGaiaAuthority(google.protobuf.message.Message):
    """The authority of a GAIA user/service account. Authentication is performed
    with OAuth2. The GAIA ID is obfuscated on the client.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    """A GAIA user is identified by its obfuscated GAIA ID."""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___ObfuscatedGaiaAuthority = ObfuscatedGaiaAuthority

class LegacyRialtoAppAuthority(google.protobuf.message.Message):
    """The authority of a Rialto application. Authentication is performed by
    comparing the Google Cloud Project API key provided in the request with the
    one stored in keystore. This authority should be limited to Coppa devices.
    No fields.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LegacyRialtoAppAuthority = LegacyRialtoAppAuthority

class AsymKeyHolderAuthority(google.protobuf.message.Message):
    """The authority of something that holds the private key. Authentication is
    performed with JWTs.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    public_key: builtins.str
    """Public key used to verify the signature of the JWT."""
    def __init__(
        self,
        *,
        public_key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["public_key", b"public_key"]) -> None: ...

global___AsymKeyHolderAuthority = AsymKeyHolderAuthority

class CurrentParticipantAuthority(google.protobuf.message.Message):
    """The authority of the current participant who claims the device. Authorization
    is performed by checking the provided end user credential.
    No fields.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CurrentParticipantAuthority = CurrentParticipantAuthority

class DataExportConfig(google.protobuf.message.Message):
    """Configuration for exporting sensor data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class BigQueryExportConfig(google.protobuf.message.Message):
        """Configuration for exporting sensor data to BigQuery."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _EchoFormat:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _EchoFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataExportConfig.BigQueryExportConfig._EchoFormat.ValueType], builtins.type):  # noqa: F821
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            ALL_FORMATS: DataExportConfig.BigQueryExportConfig._EchoFormat.ValueType  # 0
            """Export to both Legacy & Internal Echo tables."""
            LEGACY_ONLY: DataExportConfig.BigQueryExportConfig._EchoFormat.ValueType  # 1
            """Only export to Legacy Echo tables."""
            INTERNAL_ONLY: DataExportConfig.BigQueryExportConfig._EchoFormat.ValueType  # 2
            """Only export to Internal Echo tables."""

        class EchoFormat(_EchoFormat, metaclass=_EchoFormatEnumTypeWrapper):
            """Enumeration of the locations of Echo BigQuery."""

        ALL_FORMATS: DataExportConfig.BigQueryExportConfig.EchoFormat.ValueType  # 0
        """Export to both Legacy & Internal Echo tables."""
        LEGACY_ONLY: DataExportConfig.BigQueryExportConfig.EchoFormat.ValueType  # 1
        """Only export to Legacy Echo tables."""
        INTERNAL_ONLY: DataExportConfig.BigQueryExportConfig.EchoFormat.ValueType  # 2
        """Only export to Internal Echo tables."""

        class _ExportMode:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _ExportModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataExportConfig.BigQueryExportConfig._ExportMode.ValueType], builtins.type):  # noqa: F821
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            DEFAULT_GCS_ONLY: DataExportConfig.BigQueryExportConfig._ExportMode.ValueType  # 0
            """Write data to Avro files in GCS."""
            BOTH: DataExportConfig.BigQueryExportConfig._ExportMode.ValueType  # 1
            """Write files to Avro files in GCS and also stream to BQ. If this mode is
            enabled, the pubsub messages will use a dataset where it either
            replaces 'sensor_store' with 'pubsub' or prefixes the dataset with
            'pubsub_' if it doesn't contain 'sensor_store'
            """
            PUBSUB_ONLY: DataExportConfig.BigQueryExportConfig._ExportMode.ValueType  # 2
            """Publish Avro contents to PubSub (go/streaming-echo)"""

        class ExportMode(_ExportMode, metaclass=_ExportModeEnumTypeWrapper):
            """Whether to stream data into Echo or not (go/streaming-echo)."""

        DEFAULT_GCS_ONLY: DataExportConfig.BigQueryExportConfig.ExportMode.ValueType  # 0
        """Write data to Avro files in GCS."""
        BOTH: DataExportConfig.BigQueryExportConfig.ExportMode.ValueType  # 1
        """Write files to Avro files in GCS and also stream to BQ. If this mode is
        enabled, the pubsub messages will use a dataset where it either
        replaces 'sensor_store' with 'pubsub' or prefixes the dataset with
        'pubsub_' if it doesn't contain 'sensor_store'
        """
        PUBSUB_ONLY: DataExportConfig.BigQueryExportConfig.ExportMode.ValueType  # 2
        """Publish Avro contents to PubSub (go/streaming-echo)"""

        GOOGLE_CLOUD_PROJECT_ID_FIELD_NUMBER: builtins.int
        GOOGLE_CLOUD_BUCKET_NAME_FIELD_NUMBER: builtins.int
        DATASET_NAME_FIELD_NUMBER: builtins.int
        DATASET_LOCATION_FIELD_NUMBER: builtins.int
        ECHO_FORMAT_FIELD_NUMBER: builtins.int
        EXPORT_MODE_FIELD_NUMBER: builtins.int
        google_cloud_project_id: builtins.str
        """Name of the GCP project that is for data export. This may be owned by
        the SensorSuite team, or the client, depending on the case.
        `verily-sensors-batch-jobs@system.gserviceaccount.com` needs
        roles/bigquery.admin on the project.
        """
        google_cloud_bucket_name: builtins.str
        """Name of the GCS bucket to upload temporary Avro files to while loading.
        The location of this bucket must match `google_cloud_data_location`. The
        following service accounts should be granted these Storage IAM roles (see
        https://cloud.google.com/storage/docs/access-control/iam-roles):
        `lifescience-sensors-store@system.gserviceaccount.com` needs
        roles/storage.admin.
        `verily-sensors-batch-jobs@system.gserviceaccount.com` needs
        roles.storage.objectAdmin.
        """
        dataset_name: builtins.str
        """Dataset name to upload tables to. Must be a valid Dataset name,
        no spaces etc.
        lifescience-sensors-store@system.gserviceaccount.com needs
        roles/bigquery.metadataViewer on the DataSet.
        """
        dataset_location: builtins.str
        """The BigQuery Dataset location for this data"""
        echo_format: global___DataExportConfig.BigQueryExportConfig.EchoFormat.ValueType
        """Specifies if data should be exported as legacy Echo, internal Echo, or
        both.
        """
        export_mode: global___DataExportConfig.BigQueryExportConfig.ExportMode.ValueType
        """Specifies if data should be streamed to echo, written to Avro files, or
        both.
        """
        def __init__(
            self,
            *,
            google_cloud_project_id: builtins.str = ...,
            google_cloud_bucket_name: builtins.str = ...,
            dataset_name: builtins.str = ...,
            dataset_location: builtins.str = ...,
            echo_format: global___DataExportConfig.BigQueryExportConfig.EchoFormat.ValueType = ...,
            export_mode: global___DataExportConfig.BigQueryExportConfig.ExportMode.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["dataset_location", b"dataset_location", "dataset_name", b"dataset_name", "echo_format", b"echo_format", "export_mode", b"export_mode", "google_cloud_bucket_name", b"google_cloud_bucket_name", "google_cloud_project_id", b"google_cloud_project_id"]) -> None: ...

    BIG_QUERY_EXPORT_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def big_query_export_config(self) -> global___DataExportConfig.BigQueryExportConfig:
        """BigQuery data export."""
    def __init__(
        self,
        *,
        big_query_export_config: global___DataExportConfig.BigQueryExportConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["big_query_export_config", b"big_query_export_config", "data_export_type", b"data_export_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["big_query_export_config", b"big_query_export_config", "data_export_type", b"data_export_type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data_export_type", b"data_export_type"]) -> typing_extensions.Literal["big_query_export_config"] | None: ...

global___DataExportConfig = DataExportConfig

class AuthorizationDelegate(google.protobuf.message.Message):
    """An authorization backend to use for a Registry."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_NAMESPACES_FIELD_NUMBER: builtins.int
    INTERNAL_FIELD_NUMBER: builtins.int
    @property
    def participant_namespaces(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Participant.ParticipantNamespace.ValueType]:
        """Namespaces of the participants whose authorization should be delegated to
        this backend.
        """
    @property
    def internal(self) -> global___InternalAuthorizationDelegate:
        """Specification of a Borg-internal backend."""
    def __init__(
        self,
        *,
        participant_namespaces: collections.abc.Iterable[global___Participant.ParticipantNamespace.ValueType] | None = ...,
        internal: global___InternalAuthorizationDelegate | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["backend_spec", b"backend_spec", "internal", b"internal"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["backend_spec", b"backend_spec", "internal", b"internal", "participant_namespaces", b"participant_namespaces"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["backend_spec", b"backend_spec"]) -> typing_extensions.Literal["internal"] | None: ...

global___AuthorizationDelegate = AuthorizationDelegate

class InternalAuthorizationDelegate(google.protobuf.message.Message):
    """A Borg-internal server to use as an authorization delegate."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _InterfaceType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _InterfaceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[InternalAuthorizationDelegate._InterfaceType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: InternalAuthorizationDelegate._InterfaceType.ValueType  # 0
        """Reserved."""
        CSP: InternalAuthorizationDelegate._InterfaceType.ValueType  # 1
        """CSP authorization backend."""
        DMI: InternalAuthorizationDelegate._InterfaceType.ValueType  # 2
        """DMI authorization backend."""

    class InterfaceType(_InterfaceType, metaclass=_InterfaceTypeEnumTypeWrapper):
        """Enumeration of the interfaces for authorization. Each corresponds to a code
        hook.
        """

    UNKNOWN: InternalAuthorizationDelegate.InterfaceType.ValueType  # 0
    """Reserved."""
    CSP: InternalAuthorizationDelegate.InterfaceType.ValueType  # 1
    """CSP authorization backend."""
    DMI: InternalAuthorizationDelegate.InterfaceType.ValueType  # 2
    """DMI authorization backend."""

    INTERFACE_TYPE_FIELD_NUMBER: builtins.int
    DYNAMIC_STUBS_ID_FIELD_NUMBER: builtins.int
    interface_type: global___InternalAuthorizationDelegate.InterfaceType.ValueType
    """Type of the authorization interface. Corresponds to a code hook."""
    dynamic_stubs_id: builtins.str
    """ID of the dynamic stub to use. This ID maps to a Boq Dynamic Stubs
    configuration which SensorSuite backends are configured to use.
    """
    def __init__(
        self,
        *,
        interface_type: global___InternalAuthorizationDelegate.InterfaceType.ValueType = ...,
        dynamic_stubs_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dynamic_stubs_id", b"dynamic_stubs_id", "interface_type", b"interface_type"]) -> None: ...

global___InternalAuthorizationDelegate = InternalAuthorizationDelegate

class Participant(google.protobuf.message.Message):
    """A subject or patient who uses a device."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ParticipantNamespace:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ParticipantNamespaceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Participant._ParticipantNamespace.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Participant._ParticipantNamespace.ValueType  # 0
        """Reserved."""
        GAIA: Participant._ParticipantNamespace.ValueType  # 1
        """GAIA user identified by a id of the decimal representation of the user's
        GAIA ID. Supports self-auth.
        """
        MPOWER: Participant._ParticipantNamespace.ValueType  # 2
        """MPower namespace."""
        HASHED_STRING: Participant._ParticipantNamespace.ValueType  # 3
        """Hashed string namespace."""
        CSP: Participant._ParticipantNamespace.ValueType  # 4
        """CSP namespace. Supports self-auth.
        TODO(b/180118973): In SensorRegistry, this is always the internal CSP
        ID.
        """
        ANON_STUDY_DEVICE: Participant._ParticipantNamespace.ValueType  # 5
        """Anonymous study device namespace. Used when synthetic participants are
        needed.
        """
        SENSOR_REGISTRY_CUSTOM: Participant._ParticipantNamespace.ValueType  # 6
        """Custom id space for the registry. Will be prefixed by the registry ID and
        a colon (":"). For example if the Registry ID is "1-xxx-xxx" then the
        `id` should start with "1-xxx-xxx:".
        """
        OBFUSCATED_GAIA: Participant._ParticipantNamespace.ValueType  # 7
        """An obfuscated GAIA ID. For now, this is used only to support conversion
        from obfuscated GAIA IDs on clients registering devices to unobfuscated
        GAIA IDs in sensor registry.
        """
        DMI: Participant._ParticipantNamespace.ValueType  # 8
        """Users in the DMI system. Uses Userid.user_string. Caller must be
        authenticated with the DMI system. Supports self-auth.
        """
        CSP_UUID: Participant._ParticipantNamespace.ValueType  # 9
        """Chinese version of CSP namespace."""
        FIREBASE: Participant._ParticipantNamespace.ValueType  # 10
        """Firebase accounts. The `id` field is the Firebase account user ID. The
        Firebase project ID is indicated in the `firebase_project_id` field of
        RegistryPolicy. Supports self-auth.
        """

    class ParticipantNamespace(_ParticipantNamespace, metaclass=_ParticipantNamespaceEnumTypeWrapper):
        """Type of participant."""

    UNKNOWN: Participant.ParticipantNamespace.ValueType  # 0
    """Reserved."""
    GAIA: Participant.ParticipantNamespace.ValueType  # 1
    """GAIA user identified by a id of the decimal representation of the user's
    GAIA ID. Supports self-auth.
    """
    MPOWER: Participant.ParticipantNamespace.ValueType  # 2
    """MPower namespace."""
    HASHED_STRING: Participant.ParticipantNamespace.ValueType  # 3
    """Hashed string namespace."""
    CSP: Participant.ParticipantNamespace.ValueType  # 4
    """CSP namespace. Supports self-auth.
    TODO(b/180118973): In SensorRegistry, this is always the internal CSP
    ID.
    """
    ANON_STUDY_DEVICE: Participant.ParticipantNamespace.ValueType  # 5
    """Anonymous study device namespace. Used when synthetic participants are
    needed.
    """
    SENSOR_REGISTRY_CUSTOM: Participant.ParticipantNamespace.ValueType  # 6
    """Custom id space for the registry. Will be prefixed by the registry ID and
    a colon (":"). For example if the Registry ID is "1-xxx-xxx" then the
    `id` should start with "1-xxx-xxx:".
    """
    OBFUSCATED_GAIA: Participant.ParticipantNamespace.ValueType  # 7
    """An obfuscated GAIA ID. For now, this is used only to support conversion
    from obfuscated GAIA IDs on clients registering devices to unobfuscated
    GAIA IDs in sensor registry.
    """
    DMI: Participant.ParticipantNamespace.ValueType  # 8
    """Users in the DMI system. Uses Userid.user_string. Caller must be
    authenticated with the DMI system. Supports self-auth.
    """
    CSP_UUID: Participant.ParticipantNamespace.ValueType  # 9
    """Chinese version of CSP namespace."""
    FIREBASE: Participant.ParticipantNamespace.ValueType  # 10
    """Firebase accounts. The `id` field is the Firebase account user ID. The
    Firebase project ID is indicated in the `firebase_project_id` field of
    RegistryPolicy. Supports self-auth.
    """

    PARTICIPANT_NAMESPACE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    COLLECT_DATA_FIELD_NUMBER: builtins.int
    participant_namespace: global___Participant.ParticipantNamespace.ValueType
    """Type of the participant."""
    id: builtins.str
    """Identifier of the participant within its namespace."""
    collect_data: builtins.bool
    """Whether data should be collected from the associated device. Deprecated."""
    def __init__(
        self,
        *,
        participant_namespace: global___Participant.ParticipantNamespace.ValueType = ...,
        id: builtins.str = ...,
        collect_data: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["collect_data", b"collect_data", "id", b"id", "participant_namespace", b"participant_namespace"]) -> None: ...

global___Participant = Participant
