# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from verily.ds_sdk.protos import \
    management_service_pb2 as \
    verily_dot_ds__sdk_dot_protos_dot_management__service__pb2


class ManagementServiceStub(object):
    """The management API provided by the Sensor Registry allows clients to create
    devices, authenticate them, update their config, and discover them via
    different query parameters. The API is intended to be used by internal Verily
    clients like CSP, Hardware services, and other Sensor Suite services.

    API calls to any method of the Management API are authorized by the caller's
    permission in the specified device registry. Callers are identified by their
    GAIA identity using a GaiaMint with the scope. The permissions on the device
    registry are provided at the time a device registry is created and can be
    updated afterwards.
    Registries 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRegistries = channel.unary_unary(
                '/lifescience.sensors.registry.management.ManagementService/ListRegistries',
                request_serializer=verily_dot_ds__sdk_dot_protos_dot_management__service__pb2.ListRegistriesRequest.SerializeToString,
                response_deserializer=verily_dot_ds__sdk_dot_protos_dot_management__service__pb2.ListRegistriesResponse.FromString,
                )


class ManagementServiceServicer(object):
    """The management API provided by the Sensor Registry allows clients to create
    devices, authenticate them, update their config, and discover them via
    different query parameters. The API is intended to be used by internal Verily
    clients like CSP, Hardware services, and other Sensor Suite services.

    API calls to any method of the Management API are authorized by the caller's
    permission in the specified device registry. Callers are identified by their
    GAIA identity using a GaiaMint with the scope. The permissions on the device
    registry are provided at the time a device registry is created and can be
    updated afterwards.
    Registries 
    """

    def ListRegistries(self, request, context):
        """Lists the device registries that the caller has at least `VIEWER` access
        to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRegistries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRegistries,
                    request_deserializer=verily_dot_ds__sdk_dot_protos_dot_management__service__pb2.ListRegistriesRequest.FromString,
                    response_serializer=verily_dot_ds__sdk_dot_protos_dot_management__service__pb2.ListRegistriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lifescience.sensors.registry.management.ManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ManagementService(object):
    """The management API provided by the Sensor Registry allows clients to create
    devices, authenticate them, update their config, and discover them via
    different query parameters. The API is intended to be used by internal Verily
    clients like CSP, Hardware services, and other Sensor Suite services.

    API calls to any method of the Management API are authorized by the caller's
    permission in the specified device registry. Callers are identified by their
    GAIA identity using a GaiaMint with the scope. The permissions on the device
    registry are provided at the time a device registry is created and can be
    updated afterwards.
    Registries 
    """

    @staticmethod
    def ListRegistries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lifescience.sensors.registry.management.ManagementService/ListRegistries',
            verily_dot_ds__sdk_dot_protos_dot_management__service__pb2.ListRegistriesRequest.SerializeToString,
            verily_dot_ds__sdk_dot_protos_dot_management__service__pb2.ListRegistriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
