# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verily/ds_sdk/protos/management_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2

from verily.ds_sdk.protos import \
    management_resources_pb2 as \
    verily_dot_ds__sdk_dot_protos_dot_management__resources__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-verily/ds_sdk/protos/management_service.proto\x12\'lifescience.sensors.registry.management\x1a\x1cgoogle/api/annotations.proto\x1a/verily/ds_sdk/protos/management_resources.proto\"\x17\n\x15ListRegistriesRequest\"_\n\x16ListRegistriesResponse\x12\x45\n\nregistries\x18\x01 \x03(\x0b\x32\x31.lifescience.sensors.registry.management.Registry2\xbf\x01\n\x11ManagementService\x12\xa9\x01\n\x0eListRegistries\x12>.lifescience.sensors.registry.management.ListRegistriesRequest\x1a?.lifescience.sensors.registry.management.ListRegistriesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/registriesb\x06proto3')



_LISTREGISTRIESREQUEST = DESCRIPTOR.message_types_by_name['ListRegistriesRequest']
_LISTREGISTRIESRESPONSE = DESCRIPTOR.message_types_by_name['ListRegistriesResponse']
ListRegistriesRequest = _reflection.GeneratedProtocolMessageType('ListRegistriesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREGISTRIESREQUEST,
  '__module__' : 'verily.ds_sdk.protos.management_service_pb2'
  # @@protoc_insertion_point(class_scope:lifescience.sensors.registry.management.ListRegistriesRequest)
  })
_sym_db.RegisterMessage(ListRegistriesRequest)

ListRegistriesResponse = _reflection.GeneratedProtocolMessageType('ListRegistriesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTREGISTRIESRESPONSE,
  '__module__' : 'verily.ds_sdk.protos.management_service_pb2'
  # @@protoc_insertion_point(class_scope:lifescience.sensors.registry.management.ListRegistriesResponse)
  })
_sym_db.RegisterMessage(ListRegistriesResponse)

_MANAGEMENTSERVICE = DESCRIPTOR.services_by_name['ManagementService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MANAGEMENTSERVICE.methods_by_name['ListRegistries']._options = None
  _MANAGEMENTSERVICE.methods_by_name['ListRegistries']._serialized_options = b'\202\323\344\223\002\020\022\016/v1/registries'
  _LISTREGISTRIESREQUEST._serialized_start=169
  _LISTREGISTRIESREQUEST._serialized_end=192
  _LISTREGISTRIESRESPONSE._serialized_start=194
  _LISTREGISTRIESRESPONSE._serialized_end=289
  _MANAGEMENTSERVICE._serialized_start=292
  _MANAGEMENTSERVICE._serialized_end=483
# @@protoc_insertion_point(module_scope)
