"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import verily.ds_sdk.protos.enums_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class TimeInterval(google.protobuf.message.Message):
    """Message to define an arbitrary time span. This should be interpreted as a
    closed-open range.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    @property
    def start(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Start time of this interval, inclusive."""
    @property
    def end(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """End time of this interval, exclusive."""
    def __init__(
        self,
        *,
        start: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end", b"end", "start", b"start"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["end", b"end", "start", b"start"]) -> None: ...

global___TimeInterval = TimeInterval

class Application(google.protobuf.message.Message):
    """Represents a separate collection application or project within Life Sciences."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    id: verily.ds_sdk.protos.enums_pb2.ApplicationId.ValueType
    """Unique identifier for the application."""
    version: builtins.str
    """Free-form version of the application. E.g. "v1" "1.0.4"."""
    def __init__(
        self,
        *,
        id: verily.ds_sdk.protos.enums_pb2.ApplicationId.ValueType = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "version", b"version"]) -> None: ...

global___Application = Application

class AndroidMetadata(google.protobuf.message.Message):
    """Android Phone Specific info."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BRAND_FIELD_NUMBER: builtins.int
    MANUFACTURER_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    OS_VERSION_FIELD_NUMBER: builtins.int
    brand: builtins.str
    """Device brand, e.g. "Google", "Samsung", etc."""
    manufacturer: builtins.str
    """Deprecated, use `Device.manufacturer` instead."""
    model: builtins.str
    """Ex: "Nexus 5x". Deprecated, use `Device.model` instead."""
    os_version: builtins.str
    """Ex: "7.1.1". Deprecated, use `Device.os_version` instead."""
    def __init__(
        self,
        *,
        brand: builtins.str = ...,
        manufacturer: builtins.str = ...,
        model: builtins.str = ...,
        os_version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["brand", b"brand", "manufacturer", b"manufacturer", "model", b"model", "os_version", b"os_version"]) -> None: ...

global___AndroidMetadata = AndroidMetadata

class Device(google.protobuf.message.Message):
    """(-- api-linter: core::0123::resource-annotation=disabled
        aip.dev/not-precedent: This is not a resource --)
    Metadata about a device.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIAL_NUMBER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    HARDWARE_VERSION_FIELD_NUMBER: builtins.int
    FIRMWARE_VERSION_FIELD_NUMBER: builtins.int
    SOFTWARE_VERSION_FIELD_NUMBER: builtins.int
    TIME_ZONE_NAME_FIELD_NUMBER: builtins.int
    MANUFACTURER_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    OS_VERSION_FIELD_NUMBER: builtins.int
    DATA_SESSION_ID_FIELD_NUMBER: builtins.int
    ANDROID_METADATA_FIELD_NUMBER: builtins.int
    DAYLIGHT_SAVING_TIME_FIELD_NUMBER: builtins.int
    serial_number: builtins.str
    """Serial number or the device. This is a unique device identifier and must
    be present for writes. For reads at least one of serial_number and name
    must be present.
    """
    name: builtins.str
    """This field has been deprecated. It's original intended use was to
    group devices with a single name instead of having to know the serial
    number of each device. In practice, grouping is achieved by reading a
    certain type of data and leaving the device serial number unspecified
    (wildcard).
    """
    hardware_version: builtins.str
    """Version of the device's hardware. Not applicable for read requests."""
    firmware_version: builtins.str
    """Version of the device's firmware. Not applicable for read requests."""
    software_version: builtins.str
    """Version of the device's software, if any. Not applicable for read
    requests.
    """
    time_zone_name: builtins.str
    """Timezone Name/ID of the device, for eg: "America/Los_Angeles"."""
    manufacturer: builtins.str
    """Manufacturer of the device. Not applicable for read requests."""
    model: builtins.str
    """Model number of the device. Not applicable for read requests."""
    os_version: builtins.str
    """Operating system version of the device. Not applicable for read requests."""
    data_session_id: builtins.str
    """Id associated with the session the data being uploaded under.
    (eg. Virtual Serial Number)
    """
    @property
    def android_metadata(self) -> global___AndroidMetadata: ...
    daylight_saving_time: verily.ds_sdk.protos.enums_pb2.DaylightSavingTime.ValueType
    """(-- api-linter: core::0142::time-field-type=disabled
        aip.dev/not-precedent: This is not a timestamp. --)
    Whether the DST is enabled.
    """
    def __init__(
        self,
        *,
        serial_number: builtins.str = ...,
        name: builtins.str = ...,
        hardware_version: builtins.str = ...,
        firmware_version: builtins.str = ...,
        software_version: builtins.str = ...,
        time_zone_name: builtins.str = ...,
        manufacturer: builtins.str = ...,
        model: builtins.str = ...,
        os_version: builtins.str = ...,
        data_session_id: builtins.str = ...,
        android_metadata: global___AndroidMetadata | None = ...,
        daylight_saving_time: verily.ds_sdk.protos.enums_pb2.DaylightSavingTime.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["android_metadata", b"android_metadata", "device_metadata", b"device_metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["android_metadata", b"android_metadata", "data_session_id", b"data_session_id", "daylight_saving_time", b"daylight_saving_time", "device_metadata", b"device_metadata", "firmware_version", b"firmware_version", "hardware_version", b"hardware_version", "manufacturer", b"manufacturer", "model", b"model", "name", b"name", "os_version", b"os_version", "serial_number", b"serial_number", "software_version", b"software_version", "time_zone_name", b"time_zone_name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["device_metadata", b"device_metadata"]) -> typing_extensions.Literal["android_metadata"] | None: ...

global___Device = Device

class Unit(google.protobuf.message.Message):
    """Description of the unit a value is in.
    Will be evaluated as: scaleFactor * (scale * unit) ^ power
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    SCALE_FIELD_NUMBER: builtins.int
    POWER_FIELD_NUMBER: builtins.int
    SCALE_FACTOR_FIELD_NUMBER: builtins.int
    type: verily.ds_sdk.protos.enums_pb2.UnitType.ValueType
    """Type of unit."""
    scale: verily.ds_sdk.protos.enums_pb2.UnitScale.ValueType
    """Scaling factor of unit."""
    power: builtins.int
    """Power scale of unit. To make a Hertz unit, power would be -1 and type
    would be SECOND.
    """
    scale_factor: builtins.float
    """Some units are non-unit factors of SI units. This can be set here."""
    def __init__(
        self,
        *,
        type: verily.ds_sdk.protos.enums_pb2.UnitType.ValueType = ...,
        scale: verily.ds_sdk.protos.enums_pb2.UnitScale.ValueType = ...,
        power: builtins.int = ...,
        scale_factor: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["power", b"power", "scale", b"scale", "scale_factor", b"scale_factor", "type", b"type"]) -> None: ...

global___Unit = Unit

class DataFieldSpec(google.protobuf.message.Message):
    """Description of a type of data field."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    UNITS_FIELD_NUMBER: builtins.int
    PRIMITIVE_FIELD_NUMBER: builtins.int
    IS_OPTIONAL_FIELD_NUMBER: builtins.int
    ACCEPTED_STRING_VALUES_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of this field."""
    @property
    def units(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Unit]:
        """Units for this field. Units are repeated to allow construction of
        composite units types. The final unit will be the product of all Unit
        values.

        For example, a typical IMU chip would produce integer count values for
        acceleration. The values are mapped to some number of Gs. 1 G per 2000
        ints could be expressed like:
        unit { type: COUNT scale: UNIT power: -1 scale_factor: 2000}
        unit { type: ACCELERATION scale: UNIT power: 1 scale_factor: 9.8}

        Or:
        unit { type: ACCELERATION scale: UNIT power: 1 scale_factor: 0.0049}

        Or:
        unit { type: COUNT scale: UNIT power: 1 scale_factor: 0.0049}
        unit { type: METER scale: UNIT power: 1 scale_factor: 1}
        unit { type: SECOND scale: UNIT power: -2 scale_factor: 1}

        Or even:
        unit { type: COUNT scale: UNIT power: 1 scale_factor: 0.0049}
        unit { type: METER scale: UNIT power: 1 scale_factor: 1}
        unit { type: SECOND scale: UNIT power: -1 scale_factor: 1}
        unit { type: SECOND scale: UNIT power: -1 scale_factor: 1}
        """
    primitive: verily.ds_sdk.protos.enums_pb2.PrimitiveType.ValueType
    """What type of data is stored for this field. This corresponds to which
    proto field within a Value.data oneof will be set.
    """
    is_optional: builtins.bool
    """Whether this field must be present in a DataPoint for it to be valid."""
    @property
    def accepted_string_values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Only valid if primitive is STRING or STRING_LIST. Can be used to
        approximate an enum.  If not empty, DataPoint values must be one of these.
        """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        units: collections.abc.Iterable[global___Unit] | None = ...,
        primitive: verily.ds_sdk.protos.enums_pb2.PrimitiveType.ValueType = ...,
        is_optional: builtins.bool = ...,
        accepted_string_values: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["accepted_string_values", b"accepted_string_values", "is_optional", b"is_optional", "name", b"name", "primitive", b"primitive", "units", b"units"]) -> None: ...

global___DataFieldSpec = DataFieldSpec

class DataSpec(google.protobuf.message.Message):
    """Description of a type of data."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    FIELD_SPECS_FIELD_NUMBER: builtins.int
    CANONICAL_DATA_SPEC_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of a data type. This will be used to match to DataPoints by
    DataPoint.data_type_name. Can not be empty. A specific format for data
    type naming is not (currently) enforced, but it recommended to roughly
    follow java package naming conventions:
    - Use reversed domain name to begin. For example, com.verily.pulse_rate
    - All lower case to avoid conflicts.
    """
    @property
    def field_specs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DataFieldSpec]:
        """Fields that can be included in DataSets of this spec."""
    canonical_data_spec: builtins.str
    """Canonical DataSpec that is linked to this DataSpec. For example,
    'com.verily.ppg'. When data is read from the canonical DataSpec, data from
    this DataSpec (ex. 'com.verily.ppg'), then data from this DataSpec (ex.
    com.verily.studywatch.ppg') will also be read. This field will be ignored
    when writing data. Data will only be written to the DataSpec specified by
    name, above.
    TODO(b/156659863): Yet to implement.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        field_specs: collections.abc.Iterable[global___DataFieldSpec] | None = ...,
        canonical_data_spec: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["canonical_data_spec", b"canonical_data_spec", "field_specs", b"field_specs", "name", b"name"]) -> None: ...

global___DataSpec = DataSpec

class DataSource(google.protobuf.message.Message):
    """Description of a source of data. Includes where it came from and what format
    it is in.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    APPLICATION_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    DATA_SPEC_FIELD_NUMBER: builtins.int
    SENSOR_FIELD_NUMBER: builtins.int
    ALGORITHM_FIELD_NUMBER: builtins.int
    REGISTRY_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the data source."""
    @property
    def application(self) -> global___Application:
        """Application the data belongs to. Required for write requests. If
        unspecified on a read request, STUDY_KIT wil be used by default.
        This should be reserved for rare cases where data needs to be siloed by
        application.
        """
    @property
    def device(self) -> global___Device:
        """Device that generated the data."""
    @property
    def data_spec(self) -> global___DataSpec:
        """Description of the data."""
    @property
    def sensor(self) -> global___Sensor:
        """Sensor that generated the data. Useful for disambiguating multiple sensors
        on the same device and outputting the same data_spec.
        """
    @property
    def algorithm(self) -> global___Algorithm:
        """Metadata related to the algorithm that generated the data."""
    registry: builtins.str
    """The name of the registry associated with the data. Must follow the format:
    "registries/<Registry UUID>" where NAMESPACE, e.g.
    "registries/e3bc11dc-1a06-06d7-5bab-ffd8e884fe59".
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        application: global___Application | None = ...,
        device: global___Device | None = ...,
        data_spec: global___DataSpec | None = ...,
        sensor: global___Sensor | None = ...,
        algorithm: global___Algorithm | None = ...,
        registry: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["algorithm", b"algorithm", "application", b"application", "data_spec", b"data_spec", "device", b"device", "sensor", b"sensor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["algorithm", b"algorithm", "application", b"application", "data_spec", b"data_spec", "device", b"device", "name", b"name", "registry", b"registry", "sensor", b"sensor"]) -> None: ...

global___DataSource = DataSource

class Sensor(google.protobuf.message.Message):
    """Description of the sensor that took the measurement."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    """ID of the sensor. Examples: numeric ID, body location, etc."""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___Sensor = Sensor

class Algorithm(google.protobuf.message.Message):
    """A general versioning message used to indicate different methodologies or
    algorithms for various metrics.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of algorithm."""
    version: builtins.str
    """Version of algorithm."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "version", b"version"]) -> None: ...

global___Algorithm = Algorithm

class Int64List(google.protobuf.message.Message):
    """List of int64 values"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """The int64 values"""
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___Int64List = Int64List

class Float64List(google.protobuf.message.Message):
    """List of float values"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """The float values"""
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___Float64List = Float64List

class StringList(google.protobuf.message.Message):
    """List of string values"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """The string values"""
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___StringList = StringList

class BooleanList(google.protobuf.message.Message):
    """List of boolean values"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]:
        """The boolean values"""
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.bool] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___BooleanList = BooleanList

class BlobList(google.protobuf.message.Message):
    """List of blobs."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """The blob values."""
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___BlobList = BlobList

class Value(google.protobuf.message.Message):
    """A single field within a DataPoint. The value itself can have one of several
    different types.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELD_NAME_FIELD_NUMBER: builtins.int
    INT64_VALUE_FIELD_NUMBER: builtins.int
    INT64_LIST_FIELD_NUMBER: builtins.int
    FLOAT64_VALUE_FIELD_NUMBER: builtins.int
    FLOAT64_LIST_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    STRING_LIST_FIELD_NUMBER: builtins.int
    BLOB_FIELD_NUMBER: builtins.int
    ANY_FIELD_NUMBER: builtins.int
    BOOLEAN_VALUE_FIELD_NUMBER: builtins.int
    BOOLEAN_LIST_FIELD_NUMBER: builtins.int
    BLOB_LIST_FIELD_NUMBER: builtins.int
    field_name: builtins.str
    """This should match of the field name of the DataFieldSpec for this value in
    the DataSet's DataSource's DataType.
    """
    int64_value: builtins.int
    """Value as a int64."""
    @property
    def int64_list(self) -> global___Int64List:
        """Value as a list of int64s."""
    float64_value: builtins.float
    """Value as a float64."""
    @property
    def float64_list(self) -> global___Float64List:
        """Value as a list of float64s."""
    string_value: builtins.str
    """Value as a string."""
    @property
    def string_list(self) -> global___StringList:
        """Value as a list of string."""
    blob: builtins.bytes
    """Blob is intended for passing binary data (images, audio, etc.) as a field
    within a DataPoint. Metadata about the blob (encoding, sampling rate,
    encryption key name, etc) should be stored as separate fields. If no
    validation of the composite data format is needed, the Any below could be
    used instead.
    """
    @property
    def any(self) -> google.protobuf.any_pb2.Any:
        """While an arbitrary proto message with several fields can be stored as a
        single Value here, it is normally encouraged that you break your
        application specific message's fields into separate Values within the
        DataPoint (and separate DataFieldSpecs within the DataSpec). Each of
        those Values should ideally use one of the above fields. This allows the
        DataSet to still be self describing and SensorStore to validate/convert
        units as appropriate for passing data to delegates.
        """
    boolean_value: builtins.bool
    """Value as a boolean."""
    @property
    def boolean_list(self) -> global___BooleanList:
        """Value as a list of boolean."""
    @property
    def blob_list(self) -> global___BlobList:
        """Value as a list of blobs."""
    def __init__(
        self,
        *,
        field_name: builtins.str = ...,
        int64_value: builtins.int = ...,
        int64_list: global___Int64List | None = ...,
        float64_value: builtins.float = ...,
        float64_list: global___Float64List | None = ...,
        string_value: builtins.str = ...,
        string_list: global___StringList | None = ...,
        blob: builtins.bytes = ...,
        any: google.protobuf.any_pb2.Any | None = ...,
        boolean_value: builtins.bool = ...,
        boolean_list: global___BooleanList | None = ...,
        blob_list: global___BlobList | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["any", b"any", "blob", b"blob", "blob_list", b"blob_list", "boolean_list", b"boolean_list", "boolean_value", b"boolean_value", "data", b"data", "float64_list", b"float64_list", "float64_value", b"float64_value", "int64_list", b"int64_list", "int64_value", b"int64_value", "string_list", b"string_list", "string_value", b"string_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["any", b"any", "blob", b"blob", "blob_list", b"blob_list", "boolean_list", b"boolean_list", "boolean_value", b"boolean_value", "data", b"data", "field_name", b"field_name", "float64_list", b"float64_list", "float64_value", b"float64_value", "int64_list", b"int64_list", "int64_value", b"int64_value", "string_list", b"string_list", "string_value", b"string_value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["int64_value", "int64_list", "float64_value", "float64_list", "string_value", "string_list", "blob", "any", "boolean_value", "boolean_list", "blob_list"] | None: ...

global___Value = Value

class AggregatedValue(google.protobuf.message.Message):
    """A single field within a AggregatedDataPoint. The value itself can have one of
    several different types.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELD_NAME_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    SUM_FIELD_NUMBER: builtins.int
    MEAN_FIELD_NUMBER: builtins.int
    VARIANCE_FIELD_NUMBER: builtins.int
    field_name: builtins.str
    """The DataFieldSpec.name that this aggregation is computed over."""
    count: builtins.int
    """The number of entries in the aggregation bucket."""
    sum: builtins.float
    """The sum of the all the data in the aggregation bucket."""
    mean: builtins.float
    """The average (sum/count) of all the data in the aggregation bucket. If
    count is 0, the mean will be zero.
    """
    variance: builtins.float
    """The variance (E(x^2) - E(x)^2) of the data in the aggregation bucket. If
    count is 0, the mean will be zero.
    """
    def __init__(
        self,
        *,
        field_name: builtins.str = ...,
        count: builtins.int = ...,
        sum: builtins.float = ...,
        mean: builtins.float = ...,
        variance: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["count", b"count", "field_name", b"field_name", "mean", b"mean", "sum", b"sum", "variance", b"variance"]) -> None: ...

global___AggregatedValue = AggregatedValue

class OverwriteToken(google.protobuf.message.Message):
    """A key and time to mark the points as written for a batch."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OVERWRITE_KEY_FIELD_NUMBER: builtins.int
    SOURCE_DATA_VERSION_FIELD_NUMBER: builtins.int
    overwrite_key: builtins.str
    """A key that identifies this batch of points (scoped to the
    User/Device/DataSpec).
    """
    source_data_version: builtins.int
    """A generic version field that indicates staleness of DataPoints used to
    generate derived data. This field is optional and is ignored if not set.
    Will usually correspond to a timestamp in millis since epoch.
    """
    def __init__(
        self,
        *,
        overwrite_key: builtins.str = ...,
        source_data_version: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["overwrite_key", b"overwrite_key", "source_data_version", b"source_data_version"]) -> None: ...

global___OverwriteToken = OverwriteToken
